=== AlisdairM/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % mathml "mfenced|mfrac|msup||mrow|mi|mo|mn">
<!ENTITY % html "%html-inline; | %html-block; | %mathml;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements -->
<!ELEMENT math ((mrow|mi|mn|mo)*)>
<!ATTLIST math xmlns CDATA #REQUIRED>
<!ELEMENT mrow ((mfenced|mi|mo|mn|msup)*)>
<!ELEMENT mi (#PCDATA)>
<!ELEMENT mn (#PCDATA)>
<!ELEMENT mo (#PCDATA)>
<!ELEMENT mfenced (mfrac)>
<!ELEMENT msup ((mrow|mi)*)>
<!ELEMENT mfrac ((mrow|mi)*)>
<!ATTLIST mfrac linethickness CDATA #IMPLIED>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">

=== AlisdairM/LWG/xml/issue3680.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3680" status="New">
<title>Constructor of <tt>move_only_function</tt> with empty <tt><i>ref</i></tt>-qualifier is over-constrained</title>
<section><sref ref="[func.wrap.move.ctor]"/></section>
<submitter>Zhihao Yuan</submitter>
<date>27 Feb 2022</date>
<priority>2</priority>

<discussion>
<p>
The following test compiles and holds:
</p>
<blockquote><pre>
struct X
{
  int operator()() &amp; { return 1; }  // #1
  int operator()() &amp;&amp; { return 2; } // #2
};

using T = move_only_function&lt;int()&gt;;
assert(T(X{})() == 1);
</pre></blockquote>
<p>
In other words, <tt>#2</tt> is never used. But if you really remove <tt>#2</tt>, the code doesn't compile.
<p/>
The change was introduced between <paper num="P0288R5"/> and <paper num="P0288R6"/>, with 
an intention (assumed) to require <tt>move_only_function&lt;R(Args...) <i>cv</i>&gt;</tt>
erasing callable objects with <tt>operator()</tt> without <tt><i>ref</i></tt>-qualifiers. 
But the actual outcome outlawed programs that were valid when using <tt>std::function</tt>.
<p/>
It also outlaws future programs such as
</p>
<blockquote><pre>
T x = [captures](this auto&amp;) { return ...; }
</pre></blockquote>
<p>
where declaring <tt>this auto&amp;&amp;</tt> without forwarding only to satisfy
<tt>move_only_function</tt>'s constraints would be strange.
</p>

<note>2022-03-04; Reflector poll</note>
<p>
Set priority to 2 after reflector poll.
Probably needs a paper for LEWG.
</p>

</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4901"/>.
</p>

<ol>
<li><p>Modify <sref ref="[func.wrap.move.ctor]"/> as indicated:</p>

<blockquote>
<pre>
template&lt;class VT&gt;
  static constexpr bool <i>is-callable-from</i> = <i>see below</i>;
</pre>
<blockquote>
<p>
-1- If <tt><i>noex</i></tt> is <tt>true</tt>, <tt><i>is-callable-from</i>&lt;VT&gt;</tt> is equal to:
</p>
<blockquote><pre>
<del>is_nothrow_invocable_r_v&lt;R, VT <i>cv ref</i>, ArgTypes...&gt; &amp;&amp;</del>
is_nothrow_invocable_r_v&lt;R, VT <i>inv-quals</i>, ArgTypes...&gt;
</pre></blockquote>
<p>
Otherwise, <tt><i>is-callable-from</i>&lt;VT&gt;</tt> is equal to:
</p>
<blockquote><pre>
<del>is_invocable_r_v&lt;R, VT <i>cv ref</i>, ArgTypes...&gt; &amp;&amp;</del>
is_invocable_r_v&lt;R, VT <i>inv-quals</i>, ArgTypes...&gt;
</pre></blockquote>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2418.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="2418" status="WP">
<title>[fund.ts] <tt>apply</tt> does not work with member pointers</title>
<section><sref ref="[tuple.apply]"/></section>
<submitter>Zhihao Yuan</submitter>
<date>8 Jul 2014</date>
<priority>0</priority>

<discussion>
<p><b>Addresses: fund.ts</b></p>
<p>
The definition of <tt>apply</tt> present in &sect;3.2.2 [tuple.apply] prevents this
function template to be used with pointer to members type passed as the first argument.
</p>
<blockquote>
<i>Effects:</i> 
<p/>
[&hellip;]
<p/>
<tt>return std::forward&lt;F&gt;(f)(std::get&lt;I&gt;(std::forward&lt;Tuple&gt;(t))...);</tt>
</blockquote>
<p>
This makes this utility inconsistent with other standard library components and limits its usability.
<p/>
We propose to define its functionally in terms of <tt><i>INVOKE</i></tt>.
</p>

<note>2015-02, Cologne</note>
<p>
DK: We should use the new <tt>std::invoke</tt>.<br/> 
TK: Is this a defect?<br/> 
AM: <tt>std::invoke</tt> goes into C++17, and this is a defect against a TS based on C++14. We can change this later, 
but now leave it as INVOKE.<br/> 
GR: The TS lets you have Editor's Notes, so leave a note to make that change for C++17.
<p/>
[&hellip;]
<p/>
GR: I can't see how we can assume this is part of the design. I cannot believe it was ever intended for this 
design to exclude function pointers.<br/>  
AM: I can give you the exact evolution: We had "apply" as an example explaining the usefulness of <tt>index_sequence</tt>. 
Then someone looked at it and said, "why isn't this in the Standard". NJ to VV: Why are you against useful steps? 
We are trying to converge on a consistent standard across multiple documents. The alternative is to reopen this 
in a later discussion.<br/>  
VV: All I said is that this is not defect, whether or not people like it.<br/>  
AM: So you'd be fine with the issue, but not as a DR?<br/> 
Straw poll: Who's happy to make this tentatively ready as a DR against the Fundamentals TS? 
Lots of agreement, no opposition, 3 neutrals
</p>
</discussion>

<resolution>
<p>This wording is relative to <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4081.html">N4081</a> 
in regard to fundamental-ts changes.</p>

<ol>
<li><p>Edit &sect;3.2.2 [tuple.apply] paragraph 2:</p>

<blockquote>
<pre>
template &lt;class F, class Tuple&gt;
constexpr decltype(auto) apply(F&amp;&amp; f, Tuple&amp;&amp; t);
</pre>
<blockquote>
<p>
-2- <i>Effects</i>: Given the exposition only function
</p>
<blockquote>
<pre>
template &lt;class F, class Tuple, size_t... I&gt;
constexpr decltype(auto) apply_impl(  // <i>exposition only</i>
    F&amp;&amp; f, Tuple&amp;&amp; t, index_sequence&lt;I...&gt;) {
  return <ins><i>INVOKE</i>(</ins>std::forward&lt;F&gt;(f)<del>(</del><ins>, </ins>std::get&lt;I&gt;(std::forward&lt;Tuple&gt;(t))...);
}
</pre>
<p>
[&hellip;]
</p>
</blockquote>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2381.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="2381" status="New">
<title>Inconsistency in parsing floating point numbers</title>
<section><sref ref="[facet.num.get.virtuals]"/></section>
<submitter>Marshall Clow</submitter>
<date>30 Apr 2014</date>
<priority>99</priority>

<discussion>
<p>
In <sref ref="[facet.num.get.virtuals]"/> we have:
</p>
<blockquote><p>
Stage 3: The sequence of chars accumulated in stage 2 (the field) is converted to a numeric value by the
rules of one of the functions declared in the header <tt>&lt;cstdlib&gt;</tt>:
</p>
<ul>
<li><p>For a signed integer value, the function <tt>strtoll</tt>.</p></li>
<li><p>For an unsigned integer value, the function <tt>strtoull</tt>.</p></li>
<li><p>For a floating-point value, the function <tt>strtold</tt>.</p></li>
</ul>
</blockquote>
<p>
This implies that for many cases, this routine should return true:
</p>
<blockquote><pre>
bool is_same(const char* p) 
{
  std::string str{p};
  double val1 = std::strtod(str.c_str(), nullptr);
  std::stringstream ss(str);
  double val2;
  ss &gt;&gt; val2;
  return std::isinf(val1) == std::isinf(val2) &amp;&amp;                 // either they're both infinity
         std::isnan(val1) == std::isnan(val2) &amp;&amp;                 // or they're both NaN
         (std::isinf(val1) || std::isnan(val1) || val1 == val2); // or they're equal
}
</pre></blockquote>
<p>
and this is indeed true, for many strings:
</p>
<blockquote><pre>
assert(is_same("0"));
assert(is_same("1.0"));
assert(is_same("-1.0"));
assert(is_same("100.123"));
assert(is_same("1234.456e89"));
</pre></blockquote>
<p>
but not for others
</p>
<blockquote><pre>
assert(is_same("0xABp-4")); // hex float
assert(is_same("inf"));
assert(is_same("+inf"));
assert(is_same("-inf"));
assert(is_same("nan"));
assert(is_same("+nan"));
assert(is_same("-nan"));

assert(is_same("infinity"));
assert(is_same("+infinity"));
assert(is_same("-infinity"));
</pre></blockquote>
<p>
These are all strings that are correctly parsed by <tt>std::strtod</tt>, but not by the stream extraction operators.
They contain characters that are deemed invalid in stage 2 of parsing.
<p/>
If we're going to say that we're converting by the rules of <tt>strtold</tt>, then we should accept all the things that 
<tt>strtold</tt> accepts.
</p>

</discussion>

<resolution>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2844.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2844" status="Open">
<title>Stability of <tt>a_uniq.insert(i, j)</tt></title>
<section><sref ref="[associative.reqmts]"/><sref ref="[unord.req]"/></section>
<submitter>Matt Austern</submitter>
<date>14 Dec 2016</date>
<priority>3</priority>

<discussion>
<p>
If we write <tt>a_uniq.insert(i, j)</tt> and <tt>[i, j)</tt> has multiple elements with keys that compare equivalent, 
which ones get inserted? Consider, for example, inserting into a <tt>map&lt;string, int&gt;</tt> with
</p>
<blockquote><pre>
m.insert({{"red", 5}, {"green", 3}, {"red", 7}, {"blue", 2}, {"pink", 6}});
</pre></blockquote>
<p>
Which value for <tt>"red"</tt> will the map have?
<p/>
On my implementation we got <tt>"red" -&gt; 5</tt>, and I suspect that's true on most or all implementations, but I don't believe 
that's guaranteed by anything in the requirements. The wording in Table 90 just says that it "inserts each element from 
the range <tt>[i, j)</tt> if and only if there is no element with key equivalent to the key of that element", but that 
doesn't tell us what happens if <tt>[i, j)</tt> contains duplicate keys because it doesn't say what order the insertions 
are performed in. The standard should either guarantee that the first value is the one that gets inserted, or explicitly 
say that this is unspecified.
<p/>
The same issue applies to the range constructor, and to the unordered associative containers.
</p>

<note>2017-01-27 Telecon</note>
<p>Priority 3; Nico to provide wording.</p>

<note>2020-02-14, Prague</note>
<p>
LWG discussion. Suggestion to specify that we like the direction of the wording for <tt>insert</tt> of
unordered containers, but would also like to clarify that the loop is meant to be "in order" of the 
sequence elements.
<p/>
Daniel K. volunteered to provide such wording.
</p>
</discussion>

<resolution>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3633.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3633" status="New">
<title>Atomics are copy constructible and copy assignable from <tt>volatile</tt> atomics</title>
<section><sref ref="[atomics]"/></section>
<submitter>Wesley Maxey</submitter>
<date>05 Nov 2021</date>
<priority>3</priority>

<discussion>
<p>
The specification of <tt>atomic</tt> and <tt>atomic&lt;T*&gt;</tt> (in <sref ref="[atomics.types.generic.general]"/> 
and <sref ref="[atomics.types.pointer]"/>) explicitly deletes the following functions:
</p>
<blockquote>
<pre>
atomic(const atomic&amp;) = delete;
atomic&amp; operator=(const atomic&amp;) = delete;
atomic&amp; operator=(const atomic&amp;) volatile = delete;
</pre>
</blockquote>
<p>
The intent is to make atomic objects not copyable, so that initializing an atomic object 
from another atomic, or assigning an atomic object with a value from another atomic, 
must be an explicit operation.
<p/>
We also explicitly support <tt>volatile</tt> objects of types that are specializations of <tt>std::atomic</tt>; 
some of the functions that are vital for the support of volatile atomics are the following conversion operators:
</p>
<blockquote>
<pre>
operator T() const volatile noexcept; // for non-pointers
operator T*() const volatile noexcept; // for pointers
</pre>
</blockquote>
<p>
The presence of this conversion operator means that all the statements in the following piece of code 
compile successfully today, despite the deleted functions mentioned earlier:
</p>
<blockquote>
<pre>
volatile std::atomic&lt;int&gt; a;
volatile std::atomic&lt;int&gt; b(a);
std::atomic&lt;int&gt; c(a);
b = a;
c = a;
</pre>
</blockquote>
<p>
However, if <tt>a</tt> is not a volatile object, none of the last four lines compile.
</p>

<note>2022-01-29; Reflector poll</note>
<p>
Set priority to 3 after reflector poll.
<br/>
This PR would allow
<pre>
atomic&ltint&gt; x, y = std::move(x);
</pre>
because const volatile&amp; doesn't bind to rvalues. It sounds like we'll
need to delete both const volatile&amp; and const volatile&amp;&amp;.
</p>

</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4901"/>.
</p>

<ol>
<li><p>Modify <sref ref="[atomics.types.generic.general]"/>, class template <tt>atomic</tt> synopsis, as indicated:</p>

<blockquote>
<pre>
[&hellip;]
atomic(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) volatile = delete;
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[atomics.types.int]"/>, class template <tt>atomic&lt;<i>integral</i>&gt;</tt> specialization 
synopsis, as indicated:</p>

<blockquote>
<pre>
[&hellip;]
atomic(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) volatile = delete;
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[atomics.types.float]"/>, class template <tt>atomic&lt;<i>floating-point</i>&gt;</tt> specialization 
synopsis, as indicated:</p>

<blockquote>
<pre>
[&hellip;]
atomic(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) volatile = delete;
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[atomics.types.pointer]"/>, class template <tt>atomic&lt;T*&gt;</tt> partial specialization 
synopsis, as indicated:</p>

<blockquote>
<pre>
[&hellip;]
atomic(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) = delete;
atomic&amp; operator=(const <ins>volatile</ins> atomic&amp;) volatile = delete;
[&hellip;]
</pre>
</blockquote>
</li>

</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3099.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3099" status="New">
<title><tt>is_assignable&lt;Incomplete&amp;, Incomplete&amp;&gt;</tt></title>
<section><sref ref="[meta.type.synop]"/></section>
<submitter>Casey Carter</submitter>
<date>10 Apr 2018</date>
<priority>99</priority>

<discussion>
<p>
LWG <iref ref="2939"/> suggests that the the preconditions of the type traits need reevaluation.
This issue focuses specifically on <tt>is_assignable</tt> and, by extension, its variants:
<ul>
<li><tt>is_copy_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, const T&amp;&gt;</tt>,
</li>
<li><tt>is_move_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, T&gt;</tt>,
</li>
<li><tt>is_trivially_assignable&lt;T, U&gt;</tt>, equivalent to <tt>is_assignable&lt;T, U&gt; &amp;&amp;
  /* magic */</tt>,
</li>
<li><tt>is_trivially_copy_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, const T&amp;&gt; &amp;&amp;
  /* magic */</tt>,
</li>
<li><tt>is_trivially_move_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, T&gt; &amp;&amp;
  /* magic */</tt>,
</li>
<li><tt>is_nothrow_assignable&lt;T, U&gt;</tt>, equivalent to <tt>is_assignable&lt;T, U&gt; &amp;&amp;
    noexcept(declval&lt;T&gt;() = declval&lt;U&gt;())</tt>,
</li>
<li><tt>is_nothrow_copy_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, const T&amp;&gt; &amp;&amp;
    noexcept(declval&lt;T&amp;&gt;() = declval&lt;const T&amp;&gt;())</tt>,
</li>
<li><tt>is_nothrow_move_assignable&lt;T&gt;</tt>, equivalent to <tt>is_assignable&lt;T&amp;, T&gt; &amp;&amp;
    noexcept(declval&lt;T&amp;&gt;() = declval&lt;T&gt;())</tt>, and
</li>
</ul>
</p>
<p>
Firstly, we note a discrepancy: <tt>is_copy_assignable&lt;T&gt;</tt> requires <tt>T</tt> to be a complete type, but the
equivalent form <tt>is_assignable&lt;T&amp;, const T&amp;&gt;</tt> <em>does not</em>. The requirement for
<tt>is_copy_assignable&lt;T&gt;</tt> seems sensible, since there's no way to determine whether or not the assignment
<tt>declval&lt;T&amp;&gt;() = declval&lt;const T&amp;&gt;()</tt> is well-formed when <tt>T</tt> is incomplete.
It seems that the same argument should apply to all of the above "assignable" traits, and that they must require that
the referent type is complete when given a reference type parameter to be implementable.
</p>
<p>
LWG <iref ref="2729"/> constrained the copy and move assignment operators of <tt>pair</tt> and <tt>tuple</tt> to
participate in overload resolution only when all field types are copy or move assignable. These constraints interact
with the proposed fix to the preconditions of the assignable traits since both <tt>pair</tt> and <tt>tuple</tt> support
members of reference type. If we agree that (1) the assignable traits aren't implementable without the stronger
precondition, and (2) it's necessary to check the constraints at class instantiation time to constrain the assignments
(which is the case for an implementation that does not support Concepts, or wants to provide conditionally trivial
special member functions), then <tt>pair&lt;F, S&gt;</tt> (respectively <tt>tuple&lt;Ts...&gt;</tt>) must require that
<tt>remove_cvref_t&lt;F&gt;</tt> and <tt>remove_cvref_t&lt;S&gt;</tt> (respectively <tt>remove_cvref_t&lt;Ts&gt;...</tt>)
are complete types.
</p>
</discussion>

<resolution>
<p>This wording is relative to <a href="http://wg21.link/n4741">N4741</a>.</p>
<blockquote>
<ol>
<li><p>Add a new paragraph to <sref ref="[pairs.pair]"/> before paragraph 1:</p>
<blockquote>
<p><ins>-?- Both <tt>remove_cvref_t&lt;T1&gt;</tt> and <tt>remove_cvref_t&lt;T2&gt;</tt> shall be complete types.</ins></p>
<p>-1- Constructors and member functions of <tt>pair</tt> shall not throw exceptions [&hellip;]</p>
</blockquote>
</li>

<li><p>Add a new paragraph to <sref ref="[tuple.tuple]"/> after the class synopsis:</p>
<blockquote>
<p><ins>-?- All types in <tt>remove_cvref_t&lt;Types&gt;...</tt> shall be complete types.</ins></p>
</blockquote>
</li>

<li>In <sref ref="[meta.unary.prop]"/> Table 42, change the Precondition text for <tt>is_assignable</tt>,
<tt>is_trivially_assignable</tt>, and <tt>is_nothrow_assignable</tt> as follows:
<blockquote>
<ins><tt>remove_cvref_t&lt;</tt></ins><tt>T</tt><ins><tt>&gt;</tt></ins> and
<ins><tt>remove_cvref_t&lt;</tt></ins><tt>U</tt><ins><tt>&gt;</tt></ins> shall be complete types, <del><i>cv</i></del>
<tt>void</tt>, or arrays of unknown bound.
</blockquote>
</li>

<li>In <sref ref="[meta.unary.prop]"/> Table 42, change the Precondition text for <tt>is_copy_assignable</tt>,
<tt>is_move_assignable</tt>, <tt>is_trivially_copy_assignable</tt>, <tt>is_trivially_move_assignable</tt>,
<tt>is_nothrow_copy_assignable</tt>, and <tt>is_nothrow_move_assignable</tt> as follows:
<blockquote>
<ins><tt>remove_cvref_t&lt;</tt></ins><tt>T</tt><ins><tt>&gt;</tt></ins> shall be a complete type, <del><i>cv</i></del>
<tt>void</tt>, or an array of unknown bound.
</blockquote>
</li>
</ol>
</blockquote>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3779.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3779" status="Tentatively NAD">
<title><tt>ranges::fold_*</tt> can unintentionally <tt>const_cast</tt> and <tt>reinterpret_cast</tt></title>
<section><sref ref="[alg.fold]"/></section>
<submitter>Nicole Mazzuca</submitter>
<date>15 Sep 2022</date>
<priority>99</priority>

<discussion>
<p>
In the <i>Effects</i> element of <tt>ranges::fold_right</tt>, we get the following code:
</p>
<blockquote><pre>
using U = decay_t&lt;invoke_result_t&lt;F&amp;, iter_reference_t&lt;I&gt;, T&gt;&gt;;
if (first == last)
  return U(std::move(init)); // <span style="color:red;font-weight:bolder">functional-style C cast</span>
[&hellip;]
</pre></blockquote>
<p>
Given the following function object:
</p>
<blockquote><pre>
struct Second {
  static char* operator()(const char*, char* rhs) {
    return rhs;
  }
};
</pre></blockquote>
<p>
calling <tt>fold_right</tt> as:
</p>
<blockquote><pre>
char* p = fold_right(views::empty&lt;char*&gt;, "Hello", Second{});
</pre></blockquote>
<p>
initializes <tt>p</tt> with <tt>const_cast&lt;char*&gt;("Hello")</tt>.
<p/>
The same problem exists in <tt>fold_left_with_iter</tt>, and thus in <tt>fold_left</tt>.
<p/>
One can get the <tt>reinterpret_cast</tt> behavior by replacing <tt>const char*</tt> with 
<tt>unsigned long long</tt>.
</p>

<note>2022-10-12; Reflector poll</note>
<p>
Set status to "Tentatively NAD" after reflector poll.
</p>
<p>
"The example doesn't compile. The accumulator should be be the second param,
but with that fixed the constraints are not satisfied.
The <tt>convertible_to</tt> constraint prevents the undesirable casting."
</p>

</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4917"/>.
</p>

<ol>

<li><p>Modify <sref ref="[alg.fold]"/> as indicated:</p>

<blockquote>
<pre>
template&lt;bidirectional_iterator I, sentinel_for&lt;I&gt; S, class T,
         <i>indirectly-binary-right-foldable</i>&lt;T, I&gt; F&gt;
  constexpr auto ranges::fold_right(I first, S last, T init, F f);
template&lt;bidirectional_range R, class T,
         <i>indirectly-binary-right-foldable</i>&lt;T, iterator_t&lt;R&gt;&gt; F&gt;
  constexpr auto ranges::fold_right(R&amp;&amp; r, T init, F f);
</pre>
<blockquote>
<p>
-3- <i>Effects</i>: Equivalent to:
</p>
<blockquote><pre>
using U = decay_t&lt;invoke_result_t&lt;F&amp;, iter_reference_t&lt;I&gt;, T&gt;&gt;;
if (first == last)
  return <ins>static_cast&lt;</ins>U<ins>&gt;</ins>(std::move(init));
I tail = ranges::next(first, last);
U accum = invoke(f, *--tail, std::move(init));
while (first != tail)
  accum = invoke(f, *--tail, std::move(accum));
return accum;
</pre></blockquote>
</blockquote>
[&hellip;]
<pre>
template&lt;input_iterator I, sentinel_for&lt;I&gt; S, class T,
         <i>indirectly-binary-left-foldable</i>&lt;T, I&gt; F&gt;
  constexpr <i>see below</i> ranges::fold_left_with_iter(I first, S last, T init, F f);
template&lt;input_range R, class T, <i>indirectly-binary-left-foldable</i>&lt;T, iterator_t&lt;R&gt;&gt; F&gt;
  constexpr <i>see below</i> ranges::fold_left_with_iter(R&amp;&amp; r, T init, F f);
</pre>
<blockquote>
<p>
-6- Let <tt>U</tt> be <tt>decay_t&lt;invoke_result_t&lt;F&amp;, T, iter_reference_t&lt;I&gt;&gt;&gt;</tt>.
<p/>
-7- <i>Effects</i>: Equivalent to:
</p>
<blockquote><pre>
if (first == last)
  return {std::move(first), <ins>static_cast&lt;</ins>U<ins>&gt;</ins>(std::move(init))};
U accum = invoke(f, std::move(init), *first);
for (++first; first != last; ++first)
  accum = invoke(f, std::move(accum), *first);
return {std::move(first), std::move(accum)};
</pre></blockquote>
</blockquote>
</blockquote>
</li>

</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2920.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2920" status="New">
<title>Add a deduction guide for creating a shared future from a future rvalue.</title>
<section><sref ref="[futures.shared_future]"/></section>
<submitter>United States</submitter>
<date>3 Feb 2017</date>
<priority>99</priority>

<discussion>
<b>Addresses US 164</b>

<p>Add a deduction guide for creating a shared future from a future rvalue.</p>

</discussion>

<resolution>
<p>This wording is relative to <a href="http://wg21.link/n4618">N4618</a>.</p>
<ol>
<li><p>Add to the synopsis of &lt;future&gt;:</p>
<blockquote><pre><ins>
template &lt;class R&gt;
shared_future(future&lt;R&gt;&amp;&amp;) -&gt; shared_future&lt;R&gt;;
</ins></pre></blockquote>
</li>
</ol>
</resolution>

</issue>
