=== AlisdairM/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % mathml "mfenced|mfrac|msup||mrow|mi|mo|mn">
<!ENTITY % html "%html-inline; | %html-block; | %mathml;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements -->
<!ELEMENT math ((mrow|mi|mn|mo)*)>
<!ATTLIST math xmlns CDATA #REQUIRED>
<!ELEMENT mrow ((mfenced|mi|mo|mn|msup)*)>
<!ELEMENT mi (#PCDATA)>
<!ELEMENT mn (#PCDATA)>
<!ELEMENT mo (#PCDATA)>
<!ELEMENT mfenced (mfrac)>
<!ELEMENT msup ((mrow|mi)*)>
<!ELEMENT mfrac ((mrow|mi)*)>
<!ATTLIST mfrac linethickness CDATA #IMPLIED>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">

=== AlisdairM/LWG/xml/issue2737.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2737" status="New">
<title>Consider relaxing object size restrictions for single-object allocation functions</title>
<section><sref ref="[new.delete.single]"/></section>
<submitter>Clark Nelson</submitter>
<date>21 Jun 2016</date>
<priority>99</priority>

<discussion>
<p>
It should be considered whether the description of the
single-object allocation functions should say "or smaller", like
the array allocation functions. For example, according to <sref ref="[new.delete.single]"/> p1 (emphasis mine):
</p>
<blockquote>
<p>
The allocation function (3.7.4.1) called by a new-expression (5.3.4) to allocate <tt>size</tt> bytes of
storage suitably aligned to represent any object <em>of that size</em>.
</p>
</blockquote>
<p>
In contrast to this, <sref ref="[new.delete.array]"/> p1 says (emphasis mine):
</p>
<blockquote>
<p>
The allocation function (3.7.4.1) called by the array form of a new-expression (5.3.4) to allocate
<tt>size</tt> bytes of storage suitably aligned to represent any array object <em>of that size or smaller</em>. 
(footnote: It is not the direct responsibility of <tt>operator new[](std::size_t)</tt> or <tt>operator delete[](void*)</tt> 
to note the repetition count or element size of the array. Those operations are performed elsewhere in the array 
<tt>new</tt> and <tt>delete</tt> expressions. The array <tt>new</tt> expression, may, however, increase the size 
argument to operator <tt>new[](std::size_t)</tt> to obtain space to store supplemental information.)
</p>
</blockquote>
</discussion>

<resolution>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2775.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2775" status="Dup">
<title><tt>reverse_iterator</tt> is does not compile for fancy pointers</title>
<section><sref ref="[reverse.iter.elem]"/></section>
<submitter>Billy Robert O'Neal III</submitter>
<date>23 Sep 2016</date>
<priority>99</priority>

<discussion>
<duplicate><iref ref="1052"/></duplicate>
<p>
<tt>std::reverse_iterator&lt;Iterator&gt;::operator-&gt;()</tt> is specified to call <tt>addressof(operator*())</tt>,
but it returns <tt>iterator_traits&lt;Iterator&gt;::pointer</tt>, which may be a fancy pointer type from which no
conversion from <tt>T*</tt> is possible. It should instead delegate to the underlying iterator's <tt>operator-&gt;()</tt>.
</p>

<note>Issues processing Telecon 2016-10-7</note>
<p>Set status to Duplicate</p>
</discussion>

<resolution>
<p>This wording is relative to N4606.</p>

<ol>
<li><p>Modify <sref ref="[reverse.iter.opref]"/> as indicated:</p>
<blockquote>
<pre>
constexpr pointer operator-&gt;() const;
</pre>
<blockquote>
<p>
-1- <del><i>Returns:</i> <tt>addressof(operator*())</tt>.</del><ins><i>Effects:</i> If <tt>Iterator</tt>
is a pointer type, as if by:</ins>
</p>
<blockquote><pre>
<ins>Iterator tmp = current;
return --tmp;</ins>
</pre></blockquote>
<p>
<ins>Otherwise, as if by:</ins>
</p>
<blockquote><pre>
<ins>Iterator tmp = current;
--tmp;
return tmp.operator-&gt;();</ins>
</pre></blockquote>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3180.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3180" status="WP">
<title>Inconsistently named return type for <tt>ranges::minmax_element</tt></title>
<section><sref ref="[algorithm.syn]"/></section>
<submitter>Casey Carter</submitter>
<date>21 Dec 2018</date>
<priority>0</priority>

<discussion>
<p>
The overloads of <tt>std::ranges::minmax_element</tt> are specified to return
<tt>std::ranges::minmax_result</tt>, which is inconsistent with the intended
design. When an algorithm <tt>foo</tt> returns an aggregate of multiple results,
the return type should be named <tt>foo_result</tt>.
The spec should introduce an alias <tt>minmax_element_result</tt> for
<tt>minmax_result</tt> and use that alias as the return type of the
<tt>std::ranges::minmax_element</tt> overloads.
</p>

<note>2019-01-11 Status to Tentatively Ready after five positive votes on the reflector.</note>
<p>
During that reflector discussion several contributers questioned the choice of alias templates to denote
algorithm result types or particular aspects of it. Since this approach had been approved by LEWG before, 
it was suggested to those opponents to instead write a paper, because changing this as part of this issue 
would be a design change that would require a more global fixing approach.
</p>

</discussion>

<resolution>
<p>This wording is relative to <a href="https://wg21.link/n4791">N4791</a>.</p>

<ol>
<li><p>Change <sref ref="[algorithm.syn]"/> as indicated, and adjust the
declarations of <tt>std::ranges::minmax_element</tt>
in <sref ref="[alg.min.max]"/> to agree:</p>
<blockquote>
<pre>
[&hellip;]
template&lt;class ExecutionPolicy, class ForwardIterator, class Compare&gt;
  pair&lt;ForwardIterator, ForwardIterator&gt;
    minmax_element(ExecutionPolicy&amp;&amp; exec, // see <sref ref="[algorithms.parallel.overloads]"/>
                   ForwardIterator first, ForwardIterator last, Compare comp);

namespace ranges {
  <ins>template&lt;class I&gt;</ins>
  <ins>using minmax_element_result = minmax_result&lt;I&gt;;</ins>

  template&lt;ForwardIterator I, Sentinel&lt;I&gt; S, class Proj = identity,
           IndirectStrictWeakOrder&lt;projected&lt;I, Proj&gt;&gt; Comp = ranges::less&lt;&gt;&gt;
    constexpr minmax_<ins>element_</ins>result&lt;I&gt;
      minmax_element(I first, S last, Comp comp = {}, Proj proj = {});
  template&lt;ForwardRange R, class Proj = identity,
           IndirectStrictWeakOrder&lt;projected&lt;iterator_t&lt;R&gt;, Proj&gt;&gt; Comp = ranges::less&lt;&gt;&gt;
    constexpr minmax_<ins>element_</ins>result&lt;safe_iterator_t&lt;R&gt;&gt;
      minmax_element(R&amp;&amp; r, Comp comp = {}, Proj proj = {});
}

// <sref ref="[alg.clamp]"/>, bounded value
[&hellip;]
</pre>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2506.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY hellip "&#x2026;">
  <!ENTITY mdash  "&#x2014;">
] >

<issue num="2506" status="New">
<title>Underspecification of atomics</title>
<section><sref ref="[intro.multithread]"/>,<sref ref="[atomics.types.generic]"/>,<sref ref="[support.runtime]"/></section>
<submitter>Geoffrey Romer</submitter>
<date>29 May 2015</date>
<priority>99</priority>

<discussion>
<p>
The concurrency libraries specified in clauses 29 and 30 do not adequately specify how they relate to the concurrency model 
specified in <sref ref="[intro.multithread]"/>. In particular:
<p/>
<sref ref="[intro.multithread]"/> specifies "atomic objects" as having certain properties. I can only assume that instances 
of the classes defined in Clause 29 are intended to be "atomic objects" in this sense, but I can't find any wording to 
specify that, and it's genuinely unclear whether Clause 30 objects are atomic objects. In fact, on a literal reading the 
C++ Standard doesn't appear to provide <em>any</em> portable way to create an atomic object, or even determine whether an 
object is an atomic object.
<p/>
(It's not clear if the term "atomic object" is actually needed, given that atomic objects can have non-atomic operations, 
and non-atomic objects can have atomic operations. But even if the term itself goes away, there still needs to be some 
indication that Clause 29 objects have the properties currently attributed to atomic objects).
<p/>
Similarly, <sref ref="[intro.multithread]"/> uses "atomic operation" as a term of art, but the standard never unambiguously 
identifies any operation as an "atomic operation" (although in one case it unambiguously identifies an operation that is 
<em>not</em> atomic). It does come close in a few cases, but not close enough:
</p>
<ul>
<li><p><sref ref="[intro.multithread]"/>/p7 could be read to imply that "synchronization operations" in Clauses 29 and 30 
are also atomic operations. However, that's vague and indirect, and somewhat belied by <sref ref="[thread.mutex.requirements.mutex]"/>/p5, 
which specifies that mutex lock and unlock operations "behave as atomic operations", but only "for purposes of determining 
the existence of a data race". Furthermore, not a single operation in Clause 29 explicitly identifies itself as a 
"synchronization operation".</p></li>
<li><p><sref ref="[atomics.types.generic]"/>/p4 states in part that "There shall be a specialization <tt>atomic&lt;bool&gt;</tt> 
which provides the general atomic operations as specified in 29.6.1", but read in context, "general atomic operations" 
appears to be a loose synonym for "general operations on atomic types" as defined in <sref ref="[atomics.types.operations.general]"/>, 
rather than a use of "atomic object" as Words of Power. Incidentally, "atomic type" is never satisfactorily defined either 
(although the <tt>&lt;atomic&gt;</tt> synopsis comes close).</p></li>
<li><p><sref ref="[support.runtime]"/>/p10 specifies exactly which operations are "plain lock-free atomic operations", but 
in a standard where an "integral constant expression" isn't necessarily a "constant expression", I do not feel safe assuming 
that a "plain lock-free atomic operation" is an "atomic operation".</p></li>
<li><p>Hans Boehm tells me the operations with "atomically" in the Effects element are intended to be atomic operations, 
but since "atomic operation" is a term of art (e.g. in <sref ref="[intro.multithread]"/>/p27.4), I think this needs to be 
spelled out rather than assumed. Furthermore, this does not help with <sref ref="[atomics.fences]"/>, or anything in Clause 30.</p></li>
</ul>

</discussion>

<resolution>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3697.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3697" status="New">
<title>Preconditions of <tt>reference_constructs_from_temporary/reference_converts_from_temporary</tt> seem wrong</title>
<section><sref ref="[meta.unary.prop]"/></section>
<submitter>Jiang An</submitter>
<date>10 May 2022</date>
<priority>3</priority>

<discussion>
<p>
<tt>std::reference_constructs_from_temporary</tt> and <tt>std::reference_converts_from_temporary</tt> are only 
useful when <tt>T</tt> is a reference type, and a reference type is always complete. Whenever <tt>T</tt> is an 
incomplete object type, it's clear that these traits inherit from <tt>std::false_type</tt>, without any further 
detection which may result in UB. However, when <tt>T</tt> is <tt>X&amp;</tt> or <tt>X&amp;&amp;</tt> where 
<tt>X</tt> is an incomplete object type, UB may be needed because of the potentially problematic detection in 
<tt>std::is_constructible</tt> or <tt>std::is_convertible</tt>.
<p/>
I'm not sure whether the general rule in <sref ref="[meta.rqmts]"/>/5 affects these cases.
</p>

<note>2022-05-17; Reflector poll</note>
<p>
Set priority to 3 after reflector poll.
</p>

</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4910"/>.
</p>

<ol>
<li><p>Modify <sref ref="[meta.type.synop]"/>, Table 46 ([tab:meta.unary.prop]) &mdash; 
"Type property predicates" &mdash; as indicated:</p>

<blockquote>
<table border="1">
<caption>Table 46: Type property predicates [tab:meta.unary.prop]</caption>
<tr>
<th align="center">Template</th>
<th align="center">Condition</th>
<th align="center">Preconditions</th>
</tr>

<tr>
<td colspan="3" align="center">
<tt>&hellip;</tt>
</td>
</tr>

<tr>
<td>
<tt>template&lt;class T, class U&gt;<br/>
struct reference_constructs_from_temporary;</tt>
</td>

<td>
<tt>conjunction_v&lt;is_reference&lt;T&gt;, is_constructible&lt;T, U&gt;&gt;</tt> is<br/> 
<tt>true</tt>, and the initialization <tt>T t(<i>VAL</i>&lt;U&gt;);</tt> binds <tt>t</tt> to a<br/> 
temporary object whose lifetime is extended (<sref ref="[class.temporary]"/>).
</td>

<td>
<ins>If <tt>T</tt> is a reference type, <tt>remove_reference_t&lt;T&gt;</tt><br/> 
and <tt>U</tt></ins><del><tt>T</tt></del> shall be <del>a</del> complete type<ins>s</ins>,<br/>
<i>cv</i> <tt>void</tt>, or <del>an</del> array<ins>s</ins> of unknown bound.
</td>
</tr>

<tr>
<td>
<tt>template&lt;class T, class U&gt;<br/>
struct reference_converts_from_temporary;</tt>
</td>

<td>
<tt>conjunction_v&lt;is_reference&lt;T&gt;, is_convertible&lt;U, T&gt;&gt;</tt> is<br/> 
<tt>true</tt>, and the initialization <tt>T t = <i>VAL</i>&lt;U&gt;;</tt> binds <tt>t</tt> to a<br/> 
temporary object whose lifetime is extended (<sref ref="[class.temporary]"/>).
</td>

<td>
<ins>If</ins> <tt>T</tt> <ins>is a reference type, <tt>remove_reference_t&lt;T&gt;</tt></ins><br/> 
and <tt>U</tt> shall be complete types,<br/>
<i>cv</i> <tt>void</tt>, or arrays of unknown bound.
</td>
</tr>

</table>
</blockquote>

</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2769.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2769" status="Open">
<title>Redundant <tt>const</tt> in the return type of <tt>any_cast(const any&amp;)</tt></title>
<section><sref ref="[any.nonmembers]"/></section>
<submitter>Casey Carter</submitter>
<date>2 Sep 2016</date>
<priority>0</priority>

<discussion>
<p>
The overload of <tt>any_cast</tt> that accepts a reference to constant <tt>any</tt>:
</p>
<blockquote>
<pre>
template&lt;class ValueType&gt;
  ValueType any_cast(const any&amp; operand);
</pre>
</blockquote>
<p>
is specified to return <tt>*any_cast&lt;add_const_t&lt;remove_reference_t&lt;ValueType&gt;&gt;&gt;(&amp;operand)</tt> in [any.nonmembers]/5. This calls the pointer-to-constant overload of <tt>any_cast</tt>:
</p>
<blockquote>
<pre>
template&lt;class ValueType&gt;
  const ValueType* any_cast(const any* operand) noexcept;
</pre>
</blockquote>
<p>
which is specified as:
</p>
<blockquote>
<i>Returns:</i> If <tt>operand != nullptr &amp;&amp; operand-&gt;type() == typeid(ValueType)</tt>, a pointer to the object contained by <tt>operand</tt>; otherwise, <tt>nullptr</tt>.
</blockquote>
<p>
Since <tt>typeid(T) == typeid(const T)</tt> for all types <tt>T</tt>, <tt>any_cast&lt;add_const_t&lt;T&gt;&gt;(&amp;operand)</tt> is equivalent to <tt>any_cast&lt;T&gt;(&amp;operand)</tt> for all types <tt>T</tt> when operand is a constant lvalue <tt>any</tt>. 
The <tt>add_const_t</tt> in the return specification of the first overload above is therefore redundant.
</p>

<note>2016-09-09 Issues Resolution Telecon</note>
<p>P0; move to Tentatively Ready</p>
<p>Casey will provide combined wording for this and <iref ref="2768"/>, since they modify the same paragraph.</p>

<p><strong>Previous resolution [SUPERSEDED]:</strong></p>
<blockquote class="note">
<p>This wording is relative to N4606.</p>

<ol>
<li><p>Modify <sref ref="[any.nonmembers]"/> as indicated:</p>
<blockquote>
<blockquote>
<pre>
template&lt;class ValueType&gt;
  ValueType any_cast(const any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp;&amp; operand);
</pre>
</blockquote>
<p>
-4- <i>Requires:</i> <tt>is_reference_v&lt;ValueType&gt;</tt> is <tt>true</tt> or 
<tt>is_copy_constructible_v&lt;ValueType&gt;</tt> is <tt>true</tt>. Otherwise the program is ill-formed.
<p/>
-5- <i>Returns:</i> <del>For the first form, 
<tt>*any_cast&lt;add_const_t&lt;remove_reference_t&lt;ValueType&gt;&gt;&gt;(&amp;operand)</tt>. 
For the second and third forms,</del> <tt>*any_cast&lt;remove_reference_t&lt;ValueType&gt;&gt;(&amp;operand)</tt>.
<p/>
[&hellip;]
</p>
</blockquote>
</li>
</ol>
</blockquote>

<note>2016-09-09 Casey improves wording as determined by telecon</note>
<p>
The presented resolution is intended as the common wording for both LWG <iref ref="2768"/> and LWG <iref ref="2769"/>.
</p>

<p><strong>Previous resolution [SUPERSEDED]:</strong></p>
<blockquote class="note">
<p>This wording is relative to N4606.</p>

<ol>
<li><p>Modify <sref ref="[any.nonmembers]"/> as indicated:</p>
<blockquote>
<blockquote>
<pre>
template&lt;class ValueType&gt;
  ValueType any_cast(const any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp;&amp; operand);
</pre>
</blockquote>
<p>
-4- <i>Requires:</i> <tt>is_reference_v&lt;ValueType&gt;</tt> is <tt>true</tt> or 
<tt>is_copy_constructible_v&lt;ValueType&gt;</tt> is <tt>true</tt>. Otherwise the program is ill-formed.
<p/>
-5- <i>Returns:</i> For the first <del>form, 
<tt>*any_cast&lt;add_const_t&lt;remove_reference_t&lt;ValueType&gt;&gt;&gt;(&amp;operand)</tt>. 
For the</del> <ins>and</ins> second <del>and third</del> form<del>s</del>, 
<tt>*any_cast&lt;remove_reference_t&lt;ValueType&gt;&gt;(&amp;operand)</tt>. <ins>For the third form, 
<tt>std::forward&lt;ValueType&gt;(*any_cast&lt;remove_reference_t&lt;ValueType&gt;&gt;(&amp;operand))</tt>.</ins>
<p/>
[&hellip;]
</p>
</blockquote>
</li>
</ol>
</blockquote>

<note>2016-10-05, Tomasz and Casey reopen and improve the wording</note>
<p>
The constraints placed on the non-pointer <tt>any_cast</tt> overloads are neither necessary nor sufficient to 
guarantee that the specified effects are well-formed. The current PR for LWG <iref ref="2769"/> also makes it 
possible to retrieve a dangling lvalue reference to a temporary any with e.g. <tt>any_cast&lt;int&amp;&gt;(any{42})</tt>, 
which should be forbidden.
</p>

</discussion>

<resolution>
<p>This wording is relative to N4606.</p>

<ol>
<li><p>Modify <sref ref="[any.nonmembers]"/> as indicated:</p>
<blockquote>
<blockquote>
<pre>
template&lt;class ValueType&gt;
  ValueType any_cast(const any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp; operand);
template&lt;class ValueType&gt;
  ValueType any_cast(any&amp;&amp; operand);
</pre>
</blockquote>
<p>
-4- <i>Requires:</i> <del><tt>is_reference_v&lt;ValueType&gt;</tt> is <tt>true</tt> or 
<tt>is_copy_constructible_v&lt;ValueType&gt;</tt> is <tt>true</tt>.</del><ins>For the first 
overload, <tt>is_constructible_v&lt;ValueType, const remove_reference_t&lt;remove_cv_t&lt;ValueType&gt;&gt;&amp;&gt;</tt> 
is <tt>true</tt>. For the second overload, <tt>is_constructible_v&lt;ValueType, remove_reference_t&lt;remove_cv_t&lt;ValueType&gt;&gt;&amp;&gt;</tt> is <tt>true</tt>. For the third overload, <tt>is_constructible_v&lt;ValueType, 
remove_reference_t&lt;remove_cv_t&lt;ValueType&gt;&gt;&gt;</tt> is <tt>true</tt>.</ins> Otherwise the program is ill-formed.
<p/>
-5- <i>Returns:</i> For the first <del>form, 
<tt>*any_cast&lt;add_const_t&lt;remove_reference_t&lt;ValueType&gt;&gt;&gt;(&amp;operand)</tt>. 
For the</del> <ins>and</ins> second <del>and third</del> form<del>s</del>, 
<tt>*any_cast&lt;remove_reference_t&lt;ValueType&gt;&gt;(&amp;operand)</tt>. <ins>For the third form, 
<tt>std::forward&lt;ValueType&gt;(*any_cast&lt;remove_reference_t&lt;ValueType&gt;&gt;(&amp;operand))</tt>.</ins>
<p/>
[&hellip;]
</p>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3395.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3395" status="New">
<title>Definition for three-way comparison needs to be updated (US 152)</title>
<section><sref ref="[defns.comparison]"/></section>
<submitter>Jeff Garland</submitter>
<date>10 Feb 2020</date>
<priority>99</priority>

<discussion>
<p><b>Addresses <a href="https://github.com/cplusplus/nbballot/issues/151">US 152</a></b></p>
<p>
This definition in <sref ref="[defns.comparison]"/> should be updated to accommodate the new 3-way comparison operator 
(<sref ref="[expr.spaceship]"/>) as well.
</p>
</discussion>

<resolution>
<p>This wording is relative to <a href="https://wg21.link/n4849">N4849</a>.</p>

<ol>
<li><p>Modify <sref ref="[defns.comparison]"/> as indicated:</p>

<blockquote>
<p>
<b>comparison function</b>
<p/>
operator function (<sref ref="[over.oper]"/>) for any of the equality (<sref ref="[expr.eq]"/>)<ins>,</ins> 
<del>or</del> relational (<sref ref="[expr.rel]"/>)<ins>, or three-way comparison 
(<sref ref="[expr.spaceship]"/>)</ins> operators
</p>
</blockquote>
</li>

</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3537.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3537" status="New">
<title>&sect;[iterator.range] Missing <tt>noexcept</tt> for <tt>std::rbegin</tt>/<tt>rend</tt> for arrays and 
<tt>initializer_list</tt></title>
<section><sref ref="[iterator.range]"/></section>
<submitter>Jiang An</submitter>
<date>21 Mar 2021</date>
<priority>99</priority>

<discussion>
<p>
Overloads for <tt>std::rbegin</tt>/<tt>rend</tt> for built-in arrays and <tt>std::initializer_list</tt>'s has 
no preconditions and never throw exceptions, thus should be <tt>noexcept</tt>. LWG <iref ref="2280"/> 
addressed a similar issue for <tt>std::begin/end</tt>.
<p/>
Suggestion: change these declarations in <sref ref="[iterator.range]"/> (p10, 11, 12, 13) as indicated:
</p>
<blockquote>
<pre>
template&lt;class T, size_t N&gt; constexpr reverse_iterator&lt;T*&gt; rbegin(T (&amp;array)[N]) <ins>noexcept</ins>;

template&lt;class T, size_t N&gt; constexpr reverse_iterator&lt;T*&gt; rend(T (&amp;array)[N]) <ins>noexcept</ins>;

template&lt;class E&gt; constexpr reverse_iterator&lt;const E*&gt; rbegin(initializer_list&lt;E&gt; il) <ins>noexcept</ins>;

template&lt;class E&gt; constexpr reverse_iterator&lt;const E*&gt; rend(initializer_list&lt;E&gt; il) <ins>noexcept</ins>;
</pre>
</blockquote>
<p>
If this change is accepted, we may also specify <em>conditional</em> <tt>noexcept</tt> for <tt>std::crbegin/crend</tt> 
(in <sref ref="[iterator.range]"/> p14, 15), by adding <tt>noexcept(noexcept(std::rbegin/crend(c)))</tt>, like in 
LWG <iref ref="2280"/>.
<p/>
Conditional noexcept for other functions in <sref ref="[iterator.range]"/> (p2, 3, 7, 8, 16, 18, 20 22) may also be 
added for consistency.
</p>

<note>2021-03-21; Daniel comments</note>
<p>
There is intentionally no P/R provided at this point, but I'm volunteering to provide it if we got feedback whether
adding <em>conditional</em> <tt>noexcept</tt> specifiers similar to those provided by LWG <iref ref="2280"/> would
be preferred or not.
</p>
</discussion>

<resolution>
</resolution>

</issue>
