=== AlisdairM/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % mathml "mfenced|mfrac|msup||mrow|mi|mo|mn">
<!ENTITY % html "%html-inline; | %html-block; | %mathml;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements -->
<!ELEMENT math ((mrow|mi|mn|mo)*)>
<!ATTLIST math xmlns CDATA #REQUIRED>
<!ELEMENT mrow ((mfenced|mi|mo|mn|msup)*)>
<!ELEMENT mi (#PCDATA)>
<!ELEMENT mn (#PCDATA)>
<!ELEMENT mo (#PCDATA)>
<!ELEMENT mfenced (mfrac)>
<!ELEMENT msup ((mrow|mi)*)>
<!ELEMENT mfrac ((mrow|mi)*)>
<!ATTLIST mfrac linethickness CDATA #IMPLIED>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">

=== AlisdairM/LWG/xml/issue4122.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="4122" status="New">
<title>Ill-formed <tt>operator&lt;=&gt;</tt> can cause hard error when instantiating <tt>std::inplace_vector</tt></title>
<section><sref ref=" [inplace.vector.overview]"/></section>
<submitter>Jiang An</submitter>
<date>20 Jul 2024</date>
<priority>99</priority>

<discussion>
<p>
This is almost the same problem as LWG <iref ref="4071"/> except that it happens to <tt>std::inplace_vector</tt>. 
As the <tt>operator&lt;=&gt;</tt> overload for <tt>std::inplace_vector</tt> is a non-template function whose return 
type (<tt><i>synth-three-way-result</i>&lt;T&gt;</tt>) is not deduced, when the return type is ill-formed, hard 
error occurs in the instantiation of the enclosing <tt>std::inplace_vector&lt;T, N&gt;</tt>.
</p>
</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4986"/>.
</p>

<ol>
<li><p>Modify <sref ref="[inplace.vector.overview]"/>, class template <tt>std::inplace_vector</tt> synopsis, as indicated:</p>

<blockquote>
<pre>
namespace std {
  template&lt;class T, size_t N&gt;
  class inplace_vector {
  public:
    [&hellip;]
    constexpr friend bool operator==(const inplace_vector&amp; x,
                                     const inplace_vector&amp; y);
    constexpr friend <del><i>synth-three-way-result</i>&lt;T&gt;</del><ins>auto</ins>
      operator&lt;=&gt;(const inplace_vector&amp; x, const inplace_vector&amp; y)<del>;</del><ins>
        requires requires (const T t) { <i>synth-three-way</i>(t, t); } 
      {
        return lexicographical_compare_three_way(x.begin(), x.end(), y.begin(), y.end(),
                                                 <i>synth-three-way</i>);
      }</ins>
    constexpr friend void swap(inplace_vector&amp; x, inplace_vector&amp; y)
      noexcept(N == 0 || (is_nothrow_swappable_v&lt;T&gt; &amp;&amp;
                          is_nothrow_move_constructible_v&lt;T&gt;))
    { x.swap(y); }
  };
};
</pre>
</blockquote>

</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2781.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2781" status="C++17">
<title>Contradictory requirements for <tt>std::function</tt> and <tt>std::reference_wrapper</tt></title>
<section><sref ref="[func.wrap.func.con]"/></section>
<submitter>Jonathan Wakely</submitter>
<date>13 Oct 2016</date>
<priority>0</priority>

<discussion>
<p>
<tt>template&lt;class F&gt; function(F f)</tt> says that the effects are "<tt>*this</tt>
targets a copy of <tt>f</tt>" which seems pretty clear that if <tt>F</tt> is
<tt>reference_wrapper&lt;CallableType&gt;</tt> then the target is a
<tt>reference_wrapper&lt;CallableType&gt;</tt>.
<p/>
But the function copy and move constructors say "shall not throw
exceptions if <tt>f</tt>'s target is a callable object passed via
<tt>reference_wrapper</tt> or a function pointer." From the requirement above
it's impossible for the target to be "a callable object passed via
<tt>reference_wrapper</tt>" because if the function was constructed with such a
type then the target is the <tt>reference_wrapper</tt> not the callable object
it wraps.
<p/>
This matters because it affects the result of <tt>function::target_type()</tt>,
and we have implementation divergence. VC++ and libc++ store the
<tt>reference_wrapper</tt> as the target, but libstdc++ and Boost.Function
(both written by Doug Gregor) unwrap it, so the following fails:
</p>
<blockquote><pre>
#include &lt;functional&gt;
#include &lt;cassert&gt;

int main()
{
 auto f = []{};
 std::function&lt;void()&gt; fn(std::ref(f));
 assert(fn.target&lt;std::reference_wrapper&lt;decltype(f)&gt;&gt;() != nullptr);
}
</pre></blockquote>
<p>
If <tt>std::function</tt> is intended to deviate from <tt>boost::function</tt> this way
then the <i>Throws</i> element for the copy and move constructors is
misleading, and should be clarified.
</p>

<note>2016-11-12, Issaquah</note>
<p>Sat AM: Priority 0; move to Ready</p>
</discussion>

<resolution>
<p>
This wording is relative to N4606.
</p>

<ol>
<li><p>Modify <sref ref="[func.wrap.func.con]"/> p4 and p6 the same way, as shown:</p>

<blockquote>
<pre>
function(const function&amp; f);
</pre>
<blockquote>
<p>
-3- <i>Postconditions:</i> <tt>!*this</tt> if <tt>!f</tt>; otherwise, <tt>*this</tt> targets a copy of 
<tt>f.target()</tt>.
<p/>
-4- <i>Throws:</i> shall not throw exceptions if <tt>f</tt>'s target is a <del>callable object passed 
via</del><ins>specialization of</ins> <tt>reference_wrapper</tt> or a function pointer. Otherwise, may throw 
<tt>bad_alloc</tt> or any exception thrown by the copy constructor of the stored callable object. 
[<i>Note:</i> Implementations are encouraged to avoid the use of dynamically allocated memory for small 
callable objects, for example, where <tt>f</tt>'s target is an object holding only a pointer or reference to 
an object and a member function pointer. &mdash; <i>end note</i>]
</p>
</blockquote>
<pre>
function(function&amp;&amp; f);
</pre>
<blockquote>
<p>
-5- <i>Effects:</i> If <tt>!f</tt>, <tt>*this</tt> has no target; otherwise, move constructs the target of 
<tt>f</tt> into the target of <tt>*this</tt>, leaving <tt>f</tt> in a valid state with an unspecified value.
<p/>
-6- <i>Throws:</i> shall not throw exceptions if <tt>f</tt>'s target is a <del>callable object passed 
via</del><ins>specialization of</ins> <tt>reference_wrapper</tt> or a function pointer. Otherwise, may throw 
<tt>bad_alloc</tt> or any exception thrown by the copy or move constructor of the stored callable object. 
[<i>Note:</i> Implementations are encouraged to avoid the use of dynamically allocated memory for small callable 
objects, for example, where <tt>f</tt>'s target is an object holding only a pointer or reference to an object 
and a member function pointer. &mdash; <i>end note</i>]
</p>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue2309.xml
<?xml version='1.0' encoding='iso-8859-1' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="2309" status="New">
<title><tt>mutex::lock()</tt> should not throw <tt>device_or_resource_busy</tt></title>
<section><sref ref="[thread.mutex.requirements.mutex]"/></section>
<submitter>Detlef Vollmann</submitter>
<date>27 Sep 2013</date>

<discussion>
<p>
As discussed during the Chicago meeting in 
<a href="http://wiki.edg.com/twiki/bin/view/Wg21chicago2013/ThursdayMorningMinutes#LWG_2135_revisited">SG1</a>
the only reasonable reasons for throwing <tt>device_or_resource_busy</tt> seem to be:
</p>
<ul>
<li><p>
The thread currently already holds the mutex, the mutex is not recursive, and the implementation detects this.
In this case <tt>resource_deadlock_would_occur</tt> should be thrown.
</p></li>
<li><p>
Priority reasons. At least <tt>std::mutex</tt> (and possibly all standard mutex types)
should not be setup this way, otherwise we have real problems with <tt>condition_variable::wait()</tt>.
</p></li>
</ul>

<note>2014-06-17 Rapperswil</note>
<p>
Detlef provides wording
</p>
</discussion>

<resolution>
<p>This wording is relative to N3936.</p>

<ol>
<li><p>Change <sref ref="[thread.mutex.requirements.mutex]"/> as indicated:</p>

<blockquote><p>
-13- <i>Error conditions</i>:
</p>
<ul>
<li><p><tt>operation_not_permitted</tt> &mdash; if the thread does not have the privilege to perform the operation.</p></li>
<li><p><tt>resource_deadlock_would_occur</tt> &mdash; if the implementation detects that a deadlock would occur.</p></li>
<li><p><del><tt>device_or_resource_busy</tt> &mdash; if the mutex is already locked and blocking is not possible.</del></p></li>
</ul>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3002.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3002" status="C++20">
<title>[networking.ts] <tt>basic_socket_acceptor::is_open()</tt> isn't <tt>noexcept</tt></title>
<section><sref ref="[socket.acceptor.ops]"/></section>
<submitter>Jonathan Wakely</submitter>
<date>14 Jul 2017</date>
<priority>0</priority>

<discussion>
<p><b>Addresses: networking.ts</b></p>
<p>
<tt>basic_socket::is_open()</tt> is <tt>noexcept</tt>, but the corresponding function on
<tt>basic_socket_acceptor</tt> is not. This is a simple observer with a wide contract and cannot fail.</p>

<note>
2017-11-01 Moved to Tentatively Ready after 7 positive votes for P0 on c++std-lib.
</note>
<note>2018-3-17 Adopted in Jacksonville</note>
</discussion>

<resolution>
<p>This resolution is relative to <a href="https://wg21.link/n4656">N4656</a>.</p>

<ol>
<li><p>Edit <sref ref="[socket.acceptor]"/>, class template <tt>basic_socket_acceptor</tt> synopsis, as indicated:</p>

<blockquote>
<pre>
template&lt;class AcceptableProtocol&gt; 
class basic_socket_acceptor {
public:
  [&hellip;]
  bool is_open() const <ins>noexcept</ins>;
  [&hellip;]
};
</pre>
</blockquote>
</li>

<li><p>Edit <sref ref="[socket.acceptor.ops]"/> as indicated:</p>

<blockquote>
<pre>
bool is_open() const <ins>noexcept</ins>;
</pre>
<blockquote>
<p>
-10- <i>Returns:</i> A <tt>bool</tt> indicating whether this acceptor was opened by a previous call to <tt>open</tt> or <tt>assign</tt>.
</p>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>
</issue>

=== AlisdairM/LWG/xml/issue3183.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3183" status="Voting">
<title>Normative permission to specialize Ranges variable templates</title>
<section><sref ref="[iterator.concept.sizedsentinel]"/></section>
<submitter>Casey Carter</submitter>
<date>14 Jan 2019</date>
<priority>0</priority>

<discussion>
<p>
<a href="https://wg21.link/p0896r4">P0896R4 "The One Ranges Proposal"</a> added
boolean variable templates <tt>std::disable_sized_sentinel</tt> and
<tt>std::ranges::disable_sized_range</tt> which users are intended to specialize
to <tt>false</tt> for program-defined <tt>Iterator</tt>-<tt>Sentinel</tt> pairs
/ <tt>Range</tt> types which meet the syntax but do not model
the semantics of the <tt>SizedSentinel</tt> / <tt>SizedRange</tt> concepts,
respectively. Specializing these traits allows the use of such types with the
library which would otherwise treat them as if they model <tt>SizedSentinel</tt>
/ <tt>SizedRange</tt>. The wording in P0896R4 failed, however, to provide
normative permission to specialize these variable templates as is required by
<sref ref="[namespace.std]"/> after the application of
<a href="https://wg21.link/p0551r3">P0551R3</a>.
</p><p>
Furthermore, <sref ref="[namespace.std]"/> notably does not require that
program-defined specializations of standard library variable templates meet the
requirements on the primary template (as is the case for class templates) or
indeed any requirements. P0896R4 also added the <tt>enable_view</tt> variable
template which is used to explicitly opt in or out of the <tt>View</tt> concept
<sref ref="[range.view]"/> when the default chosen by the heuristic is
incorrect. P0896R4 did include normative permission to specialize
<tt>enable_view</tt>, but the wording does not place sufficient requirements on
such user specializations so as to make them usable by the <tt>View</tt> concept
definition. Specializations must be required to be usable as constant
expressions of type <tt>bool</tt> to avoid hard errors in the concept.
</p>

<note>2019-02-03 Priority to 0 and Status to Tentatively Ready after five positive votes on the reflector.</note>
</discussion>

<resolution>
<p>This wording is relative to <a href="https://wg21.link/n4791">N4791</a>.</p>

<blockquote class="note">
<p>
[<i>Drafting Note:</i> This wording uses the recently-defined core language term
"usable in constant expressions" from <sref ref="[expr.const]"/> paragraph 3
which may be unfamiliar to reviewers.]
</p>
</blockquote>

<ol>
<li><p>Change <sref ref="[iterator.concept.sizedsentinel]"/> as follows:</p>
<blockquote>
<p>
[&hellip;]
</p><p>
(2.2) &mdash; If <tt>−N</tt> is representable by
<tt>iter_difference_t&lt;I&gt;</tt>, then <tt>i - s</tt> is well-defined and
equals <tt>−N</tt>.
</p><p>
<ins>-?- Pursuant to <sref ref="[namespace.std]"/>, users may specialize
<tt>disable_sized_sentinel</tt> for cv-unqualified non-array object types
<tt>S</tt> and <tt>I</tt> at least one of which is a program-defined type.
Such specializations shall be usable in constant expressions
(<sref ref="[expr.const]"/>) and have type <tt>const bool</tt>.</ins>
</p><p>
3 [<i>Note:</i> <tt>disable_sized_sentinel</tt> allows use of sentinels and
iterators with the library that satisfy but do not in fact model
<tt>SizedSentinel</tt>.&mdash;<i>end note</i>]
</p><p>
[&hellip;]
</p>
</blockquote>
</li>
<li><p>Add an index entry for <tt>disable_sized_sentinel</tt> that points to
<sref ref="[iterator.concepts.sizedsentinel]"/>.</p>
</li>
<li><p>Change <sref ref="[range.sized]"/> as follows:</p>
<blockquote>
<p>
[&hellip;]
</p><p>
3 [<i>Note:</i> The complexity requirement for the evaluation of
<tt>ranges::size</tt> is non-amortized, unlike the case for the complexity of
the evaluations of <tt>ranges::begin</tt> and <tt>ranges::end</tt> in the
<tt>Range</tt> concept.&mdash;<i>end note</i>]
</p><p>
<ins>-?- Pursuant to <sref ref="[namespace.std]"/>, users may specialize
<tt>disable_sized_range</tt> for cv-unqualified program-defined types.
Such specializations shall be usable in constant expressions
(<sref ref="[expr.const]"/>) and have type <tt>const bool</tt>.</ins>
</p><p>
4 [<i>Note:</i> <tt>disable_sized_range</tt> allows use of range types with the
library that satisfy but do not in fact model <tt>SizedRange</tt>.&mdash;<i>end
note</i>]
</p>
</blockquote>
</li>
<li><p>Add an index entry for <tt>disable_sized_range</tt> that points to
<sref ref="[range.sized]"/>.</p>
</li>
<li><p>Change <sref ref="[range.view]"/> as follows:</p>
<blockquote>
<p>
[&hellip;]
</p><p>
5 Pursuant to <sref ref="[namespace.std]"/>, users may specialize
<tt>enable_view</tt> to <tt>true</tt> for <ins>cv-unqualified
program-defined</ins> types which model <tt>View</tt>, and <tt>false</tt> for
types which do not. <ins>Such specializations shall be usable in constant
expressions (<sref ref="[expr.const]"/>) and have type <tt>const bool</tt>.</ins>
</p>
</blockquote>
</li>
</ol>
</resolution>
</issue>

=== AlisdairM/LWG/xml/issue3732.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3732" status="C++23">
<title><tt>prepend_range</tt> and <tt>append_range</tt> can't be amortized constant time</title>
<section><sref ref="[sequence.reqmts]"/></section>
<submitter>Tim Song</submitter>
<date>06 Jul 2022</date>
<priority>99</priority>

<discussion>
<p>
<sref ref="[sequence.reqmts]"/>/69 says "An implementation shall implement them so as to take amortized constant time." 
followed by a list of operations that includes the newly added <tt>append_range</tt> and <tt>prepend_range</tt>. 
Obviously these operations cannot be implemented in amortized constant time.
<p/>
Because the actual complexity of these operations are already specified in the concrete container specification, 
we can just exclude them here.
</p>

<note>2022-08-23; Reflector poll</note>
<p>
Set status to Tentatively Ready after six votes in favour during reflector poll.
</p>

<note>2022-11-12 Approved at November 2022 meeting in Kona. Status changed: Voting &rarr; WP.</note>
</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4910"/>.
</p>

<ol>

<li><p>Modify <sref ref="[sequence.reqmts]"/> as indicated:</p>

<blockquote>
<p>
-69- The following operations are provided for some types of sequence containers but not others. <del>An implementation
shall implement them</del><ins>Operations other than <tt>prepend_range</tt> and <tt>append_range</tt> are implemented</ins> 
so as to take amortized constant time.
</p>
</blockquote>
</li>


</ol>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3637.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3637" status="New">
<title><tt>pmr::memory_resource::do_allocate</tt> needs clarification</title>
<section><sref ref="[mem.res.class]"/></section>
<submitter>Jonathan Wakely</submitter>
<date>12 Nov 2021</date>
<priority>99</priority>

<discussion>
<p>
<sref ref="[mem.res.private]"/> says that <tt>pmr::memory_resource::do_allocate</tt> 
returns "a pointer to allocated storage" and references <sref ref="[basic.stc.dynamic.allocation]"/>. 
But it's not really clear which parts of <sref ref="[basic.stc.dynamic.allocation]"/> define 
"allocated storage". <tt>pmr::memory_resource::allocate</tt> is not "an allocation function" 
and not a "replaceable allocation function", so "the value returned by a replaceable allocation 
function is a non-null pointer value" doesn't apply here, and neither does "different from any 
previously returned value".
<p/>
Is <tt>pmr::memory_resource::allocate</tt> allowed to return a null pointer on success? Is it 
allowed to return the same address twice, without an intervening deallocation? What about if you call 
<tt>pmr::monotonic_buffer_resource::release()</tt>, is that a deallocation?
<p/>
When discussed on the reflector the consensus was that returning null should not be allowed, 
it should throw an exception or return a valid dereferenceable pointer. The reference to 
<sref ref="[basic.stc.dynamic.allocation]"/> doesn't work to specify this though, so we should 
restate the requirements without directly using the core wording for <tt>operator new</tt>.
<p/>
It was also suggested that returning the same value should not be allowed without an intervening 
deallocation, but that "deallocation" should not only mean a call to deallocate on the resource, 
but include things like <tt>pmr::monotonic_buffer_resource::release()</tt>, and when a memory 
resource's destructor returns memory to an upstream resource.
</p>
</discussion>

<resolution>
</resolution>

</issue>

=== AlisdairM/LWG/xml/issue3241.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3241" status="New">
<title><tt>chrono-spec</tt> grammar ambiguity in &sect;[time.format]</title>
<section><sref ref="[time.format]"/></section>
<submitter>Victor Zverovich</submitter>
<date>24 Jul 2019</date>
<priority>99</priority>

<discussion>
<p>
The <tt>chrono-spec</tt> grammar introduced by <a href="http://wg21.link/p1361r2">P1361R2</a> "Integration 
of chrono with text formatting" in section [time.format] is ambiguous because <tt>'%'</tt> can be 
interpreted as either <tt>literal-char</tt> or <tt>conversion-spec</tt>:
</p>
<blockquote><pre>
chrono-spec     ::= literal-char | conversion-spec
literal-char    ::= &lt;a character other than '{' or '}'&gt;
conversion-spec ::= '%' [modifier] type
</pre></blockquote>
</discussion>
<resolution>
<p>This wording is relative to the Post Cologne working draft.</p>

<ol>
<li><p>Modify the <tt>literal-char</tt> grammar in [time.format] as indicated:</p>

<blockquote>
<pre>
literal-char ::= &lt;a character other than '{'<del> or</del><ins>,</ins> '}'<ins>, or '%'</ins>&gt;
</pre>
</blockquote>
</li>
</ol>
</resolution>
</issue>
